### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by trombik**
this role imlpements basic x509 certificate management.

### CODE REVIEW

**Review by mitsururike — COMMENTED** [review]
i think `x509_certificate_validate_command` is not necessary and x509_certificate_validate_command_public` and `x509_certificate_validate_command_secret` do not have to be dicts. 
do you have any plan to make the validate commands be chosen for each certificate/secret?

**Comment by trombik** [comment]
as i wrote in a issue somewhere, i would like to support other crypto tools, like `libressl`

**Comment by mitsururike** [comment]
i do not understand why `x509_certificate_validate_command_public: libressl --some-options ...` does not work.

**Comment by trombik** [comment]
~~~what if the crypto command is not openssl-compatible?~~~

you meant it should be a string. by providing dict, user does not have to lookup man page.

**Review by mitsururike — APPROVED** [review]

**Pull request merged**
